### ISSUE TITLE
Show provinces and territories boundaries

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#22]

**Comment by tomLandry** [comment]
Can we validate that again with the PVWG? Do we have confirmation it's required or desired?

**Comment by dvdkamp** [comment]
From my perspective this is necessary.

**Comment by tomLandry** [comment]
Marc-André just sent me a screenshot: https://ccdpwiki.atlassian.net/wiki/download/attachments/7503900/image.png?version=1&amp;modificationDate=1552583563059&amp;cacheVersion=1&amp;api=v2
It's indeed there, but it was difficult to view without changing transparency. Maybe that's why I haven't catched this at first glimpse. Then it becomes more a coloramp + visibility + layer order kind of thing.
