### ISSUE TITLE
Subset for data download

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#6]
- [ ] Determine the subset Ex: Province subset or temporal subset for geographical region
- [x] Download data in NETcdf format

**Comment by MarcAndreDubuc** [comment]
Derek comment: «I will suggest a few options for the approach to downloading daily data as netcdf files and post them on confluence by early next week for comments»

**Comment by dvdkamp** [comment]
Discussion around this issue has happen in a number of places, including issue #29 , and on a number of places on confluence. As such I wanted to consolidate comments and discussion here.

Here is my original discussion document that I put on confluence: 

[Options for downloading large areas of data as netcdf files Jan 15, 2019.docx](https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/files/2880502/Options.for.downloading.large.areas.of.data.as.netcdf.files.Jan.15.2019.docx)

 - comments on this file:
    - @huard:
       - Hi Derek:, Why not allow users to "click and drag" a bounding box whose area would have an upper limit corresponding to the size constraints you are suggesting ? We can then easily tweak that size limit in the frontend and this avoids the need to pre-split the data into grids. Since total size depends on time, that would give users the possibility to download large grids for a few time steps, or small grids for long periods. 
    - @MarcAndreDubuc: 
        - Hello David, In my understanding, there will be 4 ways for the user to download data. 1- A single grid-cell  2- Multiple grid-cell through a bounding box (I guest what you were referring to) 3- Through major subset of the full dataset (could be provinces for instance)  4- The whole datasets by contacting the helpdesk.  As of now, we do not know the upper limit of the solution number 2. How many grid-cell should we allow a user to take at once? Jamie Herring? Also, maybe we went on a wrong assumption here, but we think that user will need/want whole province for their work. 
    - @rod-glover provided this document as a response:
        - [Options for downloading large areas of data as netcdf files Jan 15, 2019.docx](https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/files/2880522/Options.for.downloading.large.areas.of.data.as.netcdf.files.Jan.15.2019.docx)

@dbyrns  provided [this comment](https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/29#issuecomment-463347774) in issue #29.

**Comment by dvdkamp** [comment]
From what I can tell, there are still a few un-answered questions:
  - Should we create pre-canned subsets that users can download, or should we do subsetting of .nc files on the fly, through either openDAP or wcs?
  - Should we specify the spatial subset of allow users to specify the spatial subbet and simply put a cap on the size of the subset? 
      - Both @huard and @rod-glover suggested that we allow user-specified spatial subsets. 
      - @dbyrns points out that pre-canned subsets will mean significant up-front processing time 
  - What kind of download speeds can we expect? I did a bit of wgetting .nc files from the thredds server, and I was averaging around 3.5 MB/s, I believe that @dbyrns had around a 6 MB/s rate? 
      - If the transfer rate is indeed on the order of a few MB/s, and we meet the three requirements in my [discussion document ](https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/files/2880502/Options.for.downloading.large.areas.of.data.as.netcdf.files.Jan.15.2019.docx), then the maximum size of the spatial subset will likely be on the order of the area of PEI (i.e. around 17,000 km^2)

**Comment by dvdkamp** [comment]
@MarcAndreDubuc, @tomkralidis @dbyrns,  I would suggest that this should be a point of discussion at thursday's AWG meeting?

**Comment by tomLandry** [comment]
@dvdkamp made a few downloads from CRIM, straight from HTTPS. Very fast, between 200 and 700 Mbps. This could be the best case scenario, because we're sitting on the CANARIE network just like the Ouranos server. Still indicates that from hardware perspective, random access is fast.

**Comment by dbyrns** [comment]
> * What kind of download speeds can we expect? I did a bit of wgetting .nc files from the thredds server, and I was averaging around 3.5 MB/s, I believe that @dbyrns had around a 6 MB/s rate?

I got more like 70MB/s (500Mbps) rate to achieve a 60Go in around 15minutes. But like Tom said that was using the CANARIE network. 
3.5MB/s indicate an internet access of about 30Mbps which is fairly common for household internet access. What we still not know, I guess, is the available bandwidth of Ouranos without using the CANARIE network.

**Comment by dvdkamp** [comment]
* If the transfer rate is indeed on the order of a few MB/s, and we meet the three requirements in my [discussion document ](https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/files/2880502/Options.for.downloading.large.areas.of.data.as.netcdf.files.Jan.15.2019.docx), then the maximum size of the spatial subset will likely be on the order of the area of PEI (i.e. around 17,000 km^2)
        * I got this wrong, The spatial subset would be 10x that, so around the size of New Brunswick and Nova Scotia together

**Comment by huard** [comment]
I generally agree with Rod's comments. My only concern is to make sure that downloading ensembles remains straightforward. We want users to be able to assess uncertainties, and that requires ensembles. Would an ensemble "metalink" XML file work for this use-case ?

**Comment by rod-glover** [comment]
@huard That's a valuable idea. Do you mean that the download would be an XML file containing several hyperlinks for downloading actual data? If so, I like that idea quite a lot.

That idea can fit nicely with RESTful API design, as follows: 

1. Make the ensemble "metalink" package (the XML file) is a RESTful resource:
   - Give it standard HTTP GET semantics: idempotent, safe, cacheable. 
   - What that boils down to is that it has a URL unique to that ensemble request and can be fetched (GET) from the server multiple times without causing changes to the resource. Hence easily cached.

2. Make the data hyperlinks in the ensemble resource also be RESTful resources. 
   - Give them standard HTTP GET semantics: idempotent, safe, cacheable. 
   - You'd want to put an expiry timestamp on them (in the response header), so that you don't have to keep large data files around for a long time (unless you are planning to do that; but my impression is that you are considering compuand likely ting these things on demand and transiently, which makes sense to me). The expiry time is made evident to the user in the response header or the error response should a user request a data resource that has expired. The error response body can tell also the user how to regenerate the desired data.

3. Depending on your implementation, it would be easy to return the same ensemble resource to the same or other users if they request the exact same ensemble at different times. 
   - This would essentially be based on matching the parameters of the request (ensemble, time span, spatial area, etc.) and not regenerating the package if already available. 
   - Again depending on implementation, this could save quite a lot of computation on the server side, because it is effectively caching, **and** on the client side because of the caching that the internet provides for free when one follows RESTful design (that is, adheres to the HTTP standard semantics) and sets up the caching headers properly.

I'd be happy to discuss this more if these ideas are useful to you.

**Comment by huard** [comment]
Correct. My thinking did not go as far as yours though, and I have zero experience with it myself, so caveat emptor and all that. 

There seems to be prior usage of metalinks in the climate context: https://meteo.unican.es/trac/wiki/ESGFToolsUI#ExporttoMetalink

My question is whether browsers support it ? What happens once you've downloaded the metalink file ? If users need to install something to get the files linked to in the metalink, I'm less convinced this is a good solution, and we're back to zip files.

**Comment by tomLandry** [comment]
@rod-glover On metalinks, here's a subsection from a freshly published Engineering Report from OGC Testbed-14. It does cite use of metalinks. CRIM participated quite heavily to this effort. https://docs.opengeospatial.org/per/18-050r1.html#_multiple_outputs

The report itself describes some of the current best practices on the processing side. It is safe to say that this is the latest breed of the WPS side of PAVICS. Still this is not fully integrated yet in the rest of the stack, nor is it deployed at Ouranos. Note that we will have _very very_ light funding in Testbed-15 (this year), mostly to work on climate use cases. A separate OGC pilot project on this (ESA Thematic Exploitation Platforms) is supposed to see light of day later this year - we're keeping very close eye on this.

**Comment by dbyrns** [comment]
In response to @rod-glover and @huard I agree that metalinks are more desirable than zip because of the possible caching and less processing power is required. But right now PAVICS is based on the WPS standard and even if we intend to deliver the processing over the new WPS 3.0 standard, which is based on a REST interface, this one considers the processes and jobs as REST ressources and thus multiple requests with the same parameters will always yield a new link (no caching). However if no processing are required for our needs we can still provide links directly to the thredds server which are idempotent, safe and cacheable. 

Hopefully the discussion this afternoon will shed some lights on all this.

**Comment by rod-glover** [comment]
@dbyrns You are right that POST semantics require a new resource to be created each time, there are a couple of ways to do this and have caching also. We can discuss if you would like.

**Comment by rod-glover** [comment]
@huard regarding browser support for metalinks, there are a couple of responses to this:

1. There is nothing preventing you from serving an HTML page with the hyperlinks in it. 
2. If XML is for some reason required, most browsers will present XML in a fairly readable fashion, and CSS can be applied to them to render it much more like a normal HTML page (which is a subset of XML).
3. In both cases, you don't have to force the user to "download" the metalink; they can simply view it in the browser. You can offer links for both downloading and direct viewing, the difference being what you place in the response headers.

**Comment by rod-glover** [comment]
I should add that an HTML page is (or at least can be) a REST resource. There's nothing in REST that requires resources to be represented as JSON, XML, or any other particular format, apart from internal considerations.

**Comment by dbyrns** [comment]
As describe here : https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/64520247/Architecture
We are going the simple way for the launch and provide access to full netcdf file or subsetting via opendap.
So from the AWG perspective this task is completed. 
What still need to be done is what type of subsetting do we want to offer (grid level, regions, etc.) and convert that into a list of opendap links to be indexed in the portal. Following the #55 outcome, regions could be splitted into multiple opendap links to mitigate that issue until we have time to replace the OpenDAP server.

**Comment by tomLandry** [comment]
I approve the scenarios mentionned by David and discussed at AWG. I pass the ball on this to UI considerations on https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/56 and put this issue to Done. Note that there might still be outstanding questions on subsetting, please create new issues if needed and link to this one.
