### ISSUE TITLE
Better unit management

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#68]
As reported by @habitatseven : Noticing that we don't have anywhere that spells out the units and there is a discrepancy between what the units are in the data and how they should be displayed in the maps/graphs. 

For example, some datasets are in milliseconds in the data but should probably be 'days'. Others are in Kelvin but should Celsius. 

What we need for each variable is what the unit is in the data and what the unit should be in the graphs/maps. We will need to know this to do the conversion on some of the datasets such as those in milliseconds or Kelvin.

**Comment by huard** [comment]
As a rule, XCLIM outputs temperature as K. 
Which outputs are in milliseconds ? That sounds like a bug. 
NetCDF variables should all carry the `units` attribute. If it's missing, then it's a bug, unless it's a dimensionless variable. 
You may convert K to C by subtracting 273.15.

**Comment by dvdkamp** [comment]
@habitatseven, let me know if you need some support here. Using the thredds data, CCCS can generate a table of all indices with variables if needed...

**Comment by rod-glover** [comment]
We have encountered units issues at PCIC as well. Two things have proven useful:

- Using a units library like [`pint`](https://pint.readthedocs.io/en/0.9/) to make parsing and manipulating units easy.
- Having a configuration file that gives direction on specific units issues, e.g., what the preferred unit is for a variable, and doing conversions as appropriate based on that. Sometimes it is just change of name (e.g., for precip, preferred units are mm/d; but we often have files with an equivalent but differently named unit kg m^-2 d^-1.

**Comment by huard** [comment]
Happy to report that PR https://github.com/Ouranosinc/xclim/pull/173 should address that. 
It introduces a decorator called `declare_units` that specifies either the units (e.g. K) of the dimensionality ('[temperature]'). When calling an indice function, the decorator checks that the units match. Conversion is then done as needed inside the indicator function on the inputs, and by the indicator class to make sure output units match the desired outputs. Uses pint internally. 

This will be merged once CRIM confirms that it's not breaking their prod server.

**Comment by tomLandry** [comment]
Cool. Thinking about the climate indices data that is _currently_ on Ouranos server, is a metadata update required? Does it solve problem as stated by @habitatseven?

**Comment by tlogan2000** [comment]
I believe the milliseconds bug could be in reference to this somewhat strange xarray 'feature'
https://github.com/pydata/xarray/issues/2085

I discussed with people at @habitatseven sometime last week so I think we worked it out (as long as we are discussing the same thing) ... basically if the data variable in the output netcdf indices files has a units attribute of 'days' xarray will automatically convert the datatype to a 'timedelta' object in an attempt to be helpful (it is not at all in this case!!).  

So indices such as wetdays, days>30 C etc (there are many) all get the datatype converted unless we specifically tell xarray not to.  The problem is that typically we would like the 'time' variable converted to a time object but without this accidental conversion of the data variable(s) 

to get around this we can use something like the following 
``` python
import xarray as xr
# read in data without decoding times
ds = xr.open_dataset(ncfile, decode_times=False)
# rebuild time object only for the 'time' variable
ds['time'] = xr.decode_cf(ds).time

**Comment by tlogan2000** [comment]
For the other indices it should be a simple thing to add a units column in the table here (note: this would be units stored the netcdf files):
https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/66191683/Indices+descriptions

I think temperature in kelvin would be the only thing that would have to converted before display (note we need to store the data in K for the .nc files to remain cf-compliant)

**Comment by tomLandry** [comment]
@habitatseven has been informed of this work, that is deemed sufficient. Next step is corrections/integration into the portal. Thanks all.
